import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// IMPORTA IL PROVIDER E IL BOTTONE
import { ThemeProvider } from "./components/ThemeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Protocollo Anti-Secco",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="it">
      <body className={inter.className}>
        <ThemeProvider>
          
        
          
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
