import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// IMPORTA IL PROVIDER E IL BOTTONE
import { ThemeProvider, ThemeToggle } from "./components/ThemeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Protocollo Anti-Secco",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="it">
      <body className={inter.className}>
        <ThemeProvider>
          
          {/* BOTTONE GLOBALE FISSO IN ALTO A DESTRA */}
          <div className="fixed top-4 right-4 z-[9999]">
            <ThemeToggle />
          </div>
          
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
