import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// IMPORTA IL PROVIDER E IL BOTTONE
import { ThemeProvider, ThemeToggle } from "./components/ThemeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Protocollo Anti-Secco",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="it">
      <body className={inter.className}>
        <ThemeProvider>
          
          {/* BOTTONE GLOBALE RESPONSIVE (In basso a destra su mobile, in basso a sinistra su PC) */}
<div className="fixed bottom-6 right-6 md:bottom-8 md:left-8 z-[999999]">
  <ThemeToggle />
</div>
          
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
